name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install Bazel
        run: brew install bazelisk
      - name: Set Xcode
        run: |
          XCODE_VERSION=$(cat versions.json | python3 -c 'import json,sys;obj=json.load(sys.stdin);print(obj["xcode"]);')
          sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app/Contents/Developer
      - name: Setup Dir
        run: |
          sudo mkdir -p /Users/Shared
          sudo chown -R $USER /Users/Shared
          cp -R $GITHUB_WORKSPACE /Users/Shared/telegram-ios
      - name: Build
        run: |
          SOURCE_DIR=/Users/Shared/telegram-ios
          sudo chmod -R 777 $SOURCE_DIR
          cd $SOURCE_DIR
          export BUILD_NUMBER=$(($(git rev-list --count HEAD) + $(cat build_number_offset)))
          python3 build-system/Make/ImportCertificates.py --path build-system/fake-codesigning/certs
          python3 -u build-system/Make/Make.py --bazelUserRoot="/private/var/tmp/_bazel_containerhost" build --configurationPath="build-system/appstore-configuration.json" --codesigningInformationPath=build-system/fake-codesigning --configuration=release_arm64 --buildNumber="$BUILD_NUMBER"
          mkdir -p build/artifacts
          cp $(find . -name Telegram.ipa | head -n 1) build/artifacts/
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Telegram-IPA
          path: /Users/Shared/telegram-ios/build/artifacts/Telegram.ipa
